# Generated by Django 3.2.5 on 2021-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='plataforma',
            field=models.CharField(choices=[('z', 'zoom'), ('b', 'blackboard'), ('t', 'teams'), ('c', 'classroom'), ('n', None)], default='n', max_length=2),
        ),
    ]
