# Generated by Django 3.2.5 on 2021-08-16 14:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_aula_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='dia_da_aula',
            field=models.CharField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sábado'), (5, 'Domingo')], default=datetime.date.today, max_length=20),
        ),
        migrations.AddField(
            model_name='aula',
            name='duracao_da_aula_minutos',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(600, message='Sua aula deve durar menos de 10 horas')]),
        ),
        migrations.AlterField(
            model_name='aula',
            name='plataforma',
            field=models.CharField(choices=[('z', 'zoom'), ('b', 'blackboard'), ('t', 'teams'), ('c', 'classroom'), ('n', None)], max_length=2),
        ),
    ]
