# Generated by Django 3.2.5 on 2021-08-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210816_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='horario_de_inicio',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='aula',
            name='dia_da_aula',
            field=models.SmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sábado'), (5, 'Domingo')], default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='aula',
            name='plataforma',
            field=models.CharField(choices=[('z', 'zoom'), ('b', 'blackboard'), ('t', 'teams'), ('c', 'classroom')], max_length=2),
        ),
    ]
