# Generated by Django 3.2.5 on 2021-08-16 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210816_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='horario_de_inicio',
            field=models.TimeField(default=datetime.time(1, 30)),
        ),
        migrations.AlterField(
            model_name='aula',
            name='plataforma',
            field=models.CharField(choices=[('zoom', 'zoom'), ('blackboard', 'blackboard'), ('teams', 'teams'), ('classroom', 'classroom')], default='zoom', max_length=22),
        ),
    ]
