# Generated by Django 3.2.5 on 2021-08-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_rename_link_da_aula_aula_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='link',
            field=models.URLField(default='https://jacare-tracker.web.app'),
        ),
    ]
