# Generated by Django 3.2.5 on 2021-08-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_aula_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='plataforma',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Blackboard', 'Blackboard'), ('Teams', 'Teams'), ('Classroom', 'Classroom')], default='Zoom', max_length=22),
        ),
    ]
