# Generated by Django 3.2.5 on 2021-08-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_alter_aula_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_da_aula',
            field=models.CharField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')], default='Segunda', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='plataforma',
            field=models.CharField(choices=[(0, 'Zoom'), (1, 'Blackboard'), (2, 'Teams'), (3, 'Classroom')], default='Zoom', max_length=22),
        ),
    ]
