# Generated by Django 3.2.5 on 2021-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_auto_20210820_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Zoom',
            field=models.ManyToManyField(to='crud.Zoom'),
        ),
    ]
