# Generated by Django 3.2.5 on 2021-08-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_auto_20210820_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='aula',
            name='user',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Zoom',
        ),
    ]
