# Generated by Django 3.2.5 on 2021-08-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_auto_20210823_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='password',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='user',
        ),
    ]
