# Generated by Django 3.2.5 on 2021-08-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0020_auto_20210823_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='user',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='password',
            new_name='senha',
        ),
    ]
