# Generated by Django 3.2.5 on 2021-08-23 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_auto_20210823_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_da_aula',
            field=models.CharField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')], default='Segunda', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='duracao_da_aula_minutos',
            field=models.TimeField(default=90, validators=[django.core.validators.MaxValueValidator(600, message='Sua aula deve durar menos de 10 horas')]),
        ),
    ]
