# Generated by Django 3.2.5 on 2021-08-23 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0022_auto_20210823_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='duracao_da_aula_minutos',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(600, message='Sua aula deve durar menos de 10 horas')]),
        ),
    ]
