# Generated by Django 3.2.5 on 2021-08-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_alter_aula_dia_da_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_da_aula',
            field=models.CharField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')], default=1, max_length=20),
        ),
    ]
