# Generated by Django 3.2.5 on 2021-08-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0025_alter_aula_dia_da_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_da_aula',
            field=models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='Segunda', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='link',
            field=models.URLField(default='https://teams.microsoft.com/_?tenantId=e1d017cf-c2a8-456e-8bb9-4199fc1d75bf#/conversations/Geral?threadId=19:Sk1-OVIVySVukhzW6i3uV5dw9_YbqpJOM14QIevik-41@thread.tacv2&ctx=channel'),
        ),
    ]
