# Generated by Django 3.2.5 on 2021-08-24 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0027_auto_20210824_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_da_aula',
            field=models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='Terça', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='horario_de_inicio',
            field=models.TimeField(default=datetime.datetime(2021, 8, 24, 11, 12, 51, 256037)),
        ),
    ]
